export const SET_ERROR = "SET_ERROR"
export const SET_MESSAGE = "SET_MESSAGE"

export const SET_URL = "SET_URL"
export const ADD_URL = "ADD_URL"
export const REMOVE_URL = "REMOVE_URL"
export const REMOVE_ALL_DRIVERS_BY_TYPE = "REMOVE_ALL_DRIVERS_BY_TYPE"

export const SET_CAMPAIGN_NAME = "SET_CAMPAIGN_NAME"

export const APPEND_PARAM = "APPEND_PARAM"
export const REMOVE_PARAM = "REMOVE_PARAM"

export const SET_AVAILABLE_DRIVER_TYPES = "SET_AVAILABLE_DRIVER_TYPES"
export const ADD_CHILD_URL_TO_CAMPAIGN = "ADD_CHILD_URL_TO_CAMPAIGN"
export const REMOVE_DRIVER = "REMOVE_DRIVER"